# Generated by Django 2.2.1 on 2019-08-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='no title', max_length=200)),
                ('weight_file', models.FileField(upload_to='ImageFile/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='weightfile',
            name='weight_file',
            field=models.FileField(upload_to='WeightFile/'),
        ),
    ]
