# Generated by Django 2.2.1 on 2019-08-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileManage', '0002_auto_20190819_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagefile',
            old_name='auto_increment_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='imagefile',
            old_name='weight_file',
            new_name='image_file',
        ),
        migrations.RenameField(
            model_name='weightfile',
            old_name='auto_increment_id',
            new_name='id',
        ),
    ]
